# Generated by Django 3.1.2 on 2020-12-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_auto_20201222_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraccion',
            name='pay_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.profile', verbose_name='Pagado por'),
        ),
        migrations.AlterField(
            model_name='extraccion',
            name='user_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrocaja',
            name='pay_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.profile', verbose_name='Pagado por'),
        ),
        migrations.AlterField(
            model_name='registrocaja',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
