# Generated by Django 3.1.2 on 2021-01-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20201230_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-date_created'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
