# Generated by Django 3.1.2 on 2021-01-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20210102_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
