# Generated by Django 3.1.2 on 2021-01-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20210108_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=150, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
            options={
                'verbose_name': 'Costo Extra',
                'verbose_name_plural': 'Costos Extra',
            },
        ),
    ]
