# Generated by Django 3.1.2 on 2021-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20210121_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='nozzle',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.4, max_digits=2, null=True, verbose_name='Boquilla'),
        ),
    ]
