# Generated by Django 3.1.2 on 2021-01-03 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210103_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
