# Generated by Django 3.1.2 on 2021-01-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_publication_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='detail',
            field=models.CharField(default='Ninguna', max_length=1000, verbose_name='Descripción'),
        ),
    ]
